//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ECOM_ENTITIES : DbContext
    {
        public DB_ECOM_ENTITIES()
            : base("name=DB_ECOM_ENTITIES")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ecom_address> ecom_address { get; set; }
        public virtual DbSet<ecom_adminUser> ecom_adminUser { get; set; }
        public virtual DbSet<ecom_banner> ecom_banner { get; set; }
        public virtual DbSet<ecom_banner_image> ecom_banner_image { get; set; }
        public virtual DbSet<ecom_cart> ecom_cart { get; set; }
        public virtual DbSet<ecom_category> ecom_category { get; set; }
        public virtual DbSet<ecom_category_description> ecom_category_description { get; set; }
        public virtual DbSet<ecom_country> ecom_country { get; set; }
        public virtual DbSet<ecom_coupon> ecom_coupon { get; set; }
        public virtual DbSet<ecom_coupon_history> ecom_coupon_history { get; set; }
        public virtual DbSet<ecom_coupon_product> ecom_coupon_product { get; set; }
        public virtual DbSet<ecom_currency> ecom_currency { get; set; }
        public virtual DbSet<ecom_customer> ecom_customer { get; set; }
        public virtual DbSet<ecom_customer_ip> ecom_customer_ip { get; set; }
        public virtual DbSet<ecom_customer_login> ecom_customer_login { get; set; }
        public virtual DbSet<ecom_customer_reward> ecom_customer_reward { get; set; }
        public virtual DbSet<ecom_customer_transaction> ecom_customer_transaction { get; set; }
        public virtual DbSet<ecom_filter> ecom_filter { get; set; }
        public virtual DbSet<ecom_filter_group> ecom_filter_group { get; set; }
        public virtual DbSet<ecom_language> ecom_language { get; set; }
        public virtual DbSet<ecom_manufacturer> ecom_manufacturer { get; set; }
        public virtual DbSet<ecom_option> ecom_option { get; set; }
        public virtual DbSet<ecom_option_value> ecom_option_value { get; set; }
        public virtual DbSet<ecom_order> ecom_order { get; set; }
        public virtual DbSet<ecom_order_history> ecom_order_history { get; set; }
        public virtual DbSet<ecom_order_option> ecom_order_option { get; set; }
        public virtual DbSet<ecom_order_product> ecom_order_product { get; set; }
        public virtual DbSet<ecom_order_recurring> ecom_order_recurring { get; set; }
        public virtual DbSet<ecom_order_recurring_transaction> ecom_order_recurring_transaction { get; set; }
        public virtual DbSet<ecom_order_shipment> ecom_order_shipment { get; set; }
        public virtual DbSet<ecom_order_status> ecom_order_status { get; set; }
        public virtual DbSet<ecom_order_total> ecom_order_total { get; set; }
        public virtual DbSet<ecom_order_voucher> ecom_order_voucher { get; set; }
        public virtual DbSet<ecom_product> ecom_product { get; set; }
        public virtual DbSet<ecom_product_attribute> ecom_product_attribute { get; set; }
        public virtual DbSet<ecom_product_discount> ecom_product_discount { get; set; }
        public virtual DbSet<ecom_product_image> ecom_product_image { get; set; }
        public virtual DbSet<ecom_product_option> ecom_product_option { get; set; }
        public virtual DbSet<ecom_product_option_value> ecom_product_option_value { get; set; }
        public virtual DbSet<ecom_product_reward> ecom_product_reward { get; set; }
        public virtual DbSet<ecom_product_special> ecom_product_special { get; set; }
        public virtual DbSet<ecom_product_to_download> ecom_product_to_download { get; set; }
        public virtual DbSet<ecom_product_to_layout> ecom_product_to_layout { get; set; }
        public virtual DbSet<ecom_setting> ecom_setting { get; set; }
        public virtual DbSet<ecom_store> ecom_store { get; set; }
        public virtual DbSet<ecom_tax_class> ecom_tax_class { get; set; }
        public virtual DbSet<ecom_tax_rate> ecom_tax_rate { get; set; }
        public virtual DbSet<ecom_tax_rate_to_customer_group> ecom_tax_rate_to_customer_group { get; set; }
        public virtual DbSet<ecom_tax_rule> ecom_tax_rule { get; set; }
        public virtual DbSet<ecom_tt_blog> ecom_tt_blog { get; set; }
        public virtual DbSet<ecom_tt_blog_comment> ecom_tt_blog_comment { get; set; }
        public virtual DbSet<ecom_user> ecom_user { get; set; }
        public virtual DbSet<ecom_user_group> ecom_user_group { get; set; }
        public virtual DbSet<ecom_weight_class> ecom_weight_class { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ecom_category_filter> ecom_category_filter { get; set; }
        public virtual DbSet<ecom_coupon_category> ecom_coupon_category { get; set; }
        public virtual DbSet<ecom_customer_wishlist> ecom_customer_wishlist { get; set; }
        public virtual DbSet<ecom_filter_description> ecom_filter_description { get; set; }
        public virtual DbSet<ecom_filter_group_description> ecom_filter_group_description { get; set; }
        public virtual DbSet<ecom_manufacturer_to_store> ecom_manufacturer_to_store { get; set; }
        public virtual DbSet<ecom_option_description> ecom_option_description { get; set; }
        public virtual DbSet<ecom_option_value_description> ecom_option_value_description { get; set; }
        public virtual DbSet<ecom_product_description> ecom_product_description { get; set; }
        public virtual DbSet<ecom_product_filter> ecom_product_filter { get; set; }
        public virtual DbSet<ecom_product_recurring> ecom_product_recurring { get; set; }
        public virtual DbSet<ecom_product_related> ecom_product_related { get; set; }
        public virtual DbSet<ecom_product_to_category> ecom_product_to_category { get; set; }
        public virtual DbSet<ecom_product_to_store> ecom_product_to_store { get; set; }
        public virtual DbSet<ecom_tt_blog_comment_description> ecom_tt_blog_comment_description { get; set; }
        public virtual DbSet<ecom_tt_blog_description> ecom_tt_blog_description { get; set; }
        public virtual DbSet<ecom_weight_class_description> ecom_weight_class_description { get; set; }
    }
}
