//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecom_tax_rule
    {
        public int tax_rule_id { get; set; }
        public int tax_class_id { get; set; }
        public int tax_rate_id { get; set; }
        public string based { get; set; }
        public int priority { get; set; }
    }
}
