//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecom_customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ecom_customer()
        {
            this.ecom_address = new HashSet<ecom_address>();
            this.ecom_cart = new HashSet<ecom_cart>();
            this.ecom_customer_ip = new HashSet<ecom_customer_ip>();
            this.ecom_order = new HashSet<ecom_order>();
        }
    
        public int customer_id { get; set; }
        public int customer_group_id { get; set; }
        public int store_id { get; set; }
        public int language_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string cart { get; set; }
        public string wishlist { get; set; }
        public byte newsletter { get; set; }
        public int address_id { get; set; }
        public string custom_field { get; set; }
        public string ip { get; set; }
        public byte status { get; set; }
        public byte safe { get; set; }
        public string token { get; set; }
        public string code { get; set; }
        public System.DateTime date_added { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_address> ecom_address { get; set; }
        public virtual ecom_address ecom_address1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_cart> ecom_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_customer_ip> ecom_customer_ip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_order> ecom_order { get; set; }
    }
}
