//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecom_language
    {
        public int language_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string locale { get; set; }
        public string image { get; set; }
        public string directory { get; set; }
        public int sort_order { get; set; }
        public byte status { get; set; }
    }
}
