//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecom_category_description
    {
        public int categorydescription_id { get; set; }
        public int category_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string meta_title { get; set; }
        public string meta_description { get; set; }
        public string meta_keyword { get; set; }
    }
}
