//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecom_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ecom_product()
        {
            this.ecom_product_attribute = new HashSet<ecom_product_attribute>();
            this.ecom_product_description = new HashSet<ecom_product_description>();
            this.ecom_product_discount = new HashSet<ecom_product_discount>();
            this.ecom_product_image = new HashSet<ecom_product_image>();
            this.ecom_product_option = new HashSet<ecom_product_option>();
            this.ecom_product_related = new HashSet<ecom_product_related>();
            this.ecom_product_reward = new HashSet<ecom_product_reward>();
            this.ecom_product_special = new HashSet<ecom_product_special>();
            this.ecom_product_to_category = new HashSet<ecom_product_to_category>();
            this.ecom_product_to_layout = new HashSet<ecom_product_to_layout>();
            this.ecom_product_to_store = new HashSet<ecom_product_to_store>();
        }
    
        public int product_id { get; set; }
        public string model { get; set; }
        public string sku { get; set; }
        public string upc { get; set; }
        public string ean { get; set; }
        public string jan { get; set; }
        public string isbn { get; set; }
        public string mpn { get; set; }
        public string location { get; set; }
        public int quantity { get; set; }
        public int stock_status_id { get; set; }
        public string image { get; set; }
        public int manufacturer_id { get; set; }
        public byte shipping { get; set; }
        public decimal price { get; set; }
        public int points { get; set; }
        public int tax_class_id { get; set; }
        public System.DateTime date_available { get; set; }
        public decimal weight { get; set; }
        public int weight_class_id { get; set; }
        public decimal length { get; set; }
        public decimal width { get; set; }
        public decimal height { get; set; }
        public int length_class_id { get; set; }
        public byte subtract { get; set; }
        public int minimum { get; set; }
        public int sort_order { get; set; }
        public byte status { get; set; }
        public int viewed { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual ecom_manufacturer ecom_manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_attribute> ecom_product_attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_description> ecom_product_description { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_discount> ecom_product_discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_image> ecom_product_image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_option> ecom_product_option { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_related> ecom_product_related { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_reward> ecom_product_reward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_special> ecom_product_special { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_to_category> ecom_product_to_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_to_layout> ecom_product_to_layout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecom_product_to_store> ecom_product_to_store { get; set; }
    }
}
