//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecom_customer_ip
    {
        public int customer_ip_id { get; set; }
        public int customer_id { get; set; }
        public string ip { get; set; }
        public System.DateTime date_added { get; set; }
    
        public virtual ecom_customer ecom_customer { get; set; }
    }
}
