//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecom_cart
    {
        public int cart_id { get; set; }
        public int api_id { get; set; }
        public int customer_id { get; set; }
        public string session_id { get; set; }
        public int product_id { get; set; }
        public int recurring_id { get; set; }
        public string option { get; set; }
        public int quantity { get; set; }
        public System.DateTime date_adde { get; set; }
    
        public virtual ecom_customer ecom_customer { get; set; }
    }
}
