//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecom_tt_blog
    {
        public int tt_blog_id { get; set; }
        public int module_id { get; set; }
        public int status { get; set; }
        public string image { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
